// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oavmbvoprdpwioytbiee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdm1idm9wcmRwd2lveXRiaWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTY1NjQsImV4cCI6MjA2NzI5MjU2NH0.kiiz6L6qejzdY_rj2WAUoTvAhD687lHTzR5nHZJJwvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});